-- 0006: global settings and the singleton install_state FSM that drives the setup
-- wizard. Structural seed only (the singleton row + non-secret defaults). The
-- admin user, storage cluster, and first org/project are created at RUNTIME by the
-- wizard (so secrets are generated by crypto/rand), NOT seeded here.

CREATE TABLE system_settings (
    key         text        PRIMARY KEY,
    value       jsonb       NOT NULL,
    is_secret   boolean     NOT NULL DEFAULT false,   -- encrypted-at-rest if true
    description text,
    updated_by  uuid        REFERENCES users(id) ON DELETE SET NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_system_settings_updated_at BEFORE UPDATE ON system_settings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE install_state (
    id             integer      PRIMARY KEY DEFAULT 1 CHECK (id = 1),  -- singleton
    step           install_step NOT NULL DEFAULT 'created',
    schema_version text,
    instance_id    uuid         NOT NULL DEFAULT gen_random_uuid(),    -- stable install identity
    completed_at   timestamptz,
    details        jsonb        NOT NULL DEFAULT '{}',                 -- per-step checkpoints (idempotency)
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_install_state_updated_at BEFORE UPDATE ON install_state
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Structural seed: the singleton install_state row + non-secret default settings.
INSERT INTO install_state (id, step) VALUES (1, 'created');

INSERT INTO system_settings (key, value, description) VALUES
    ('garage.pinned_version', '"v2.3.0"',  'Pinned Garage image/binary version'),
    ('garage.default_db_engine', '"sqlite"', 'Default Garage storage engine for new clusters'),
    ('branding.product_name', '"buktio"',   'Display name shown in the panel');
