{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "buktio.fullname" . }}-postgres
  labels: {{- include "buktio.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "buktio.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels: {{- include "buktio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels: {{- include "buktio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | quote }}
          ports:
            - { name: pg, containerPort: 5432 }
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: {{ include "buktio.fullname" . }}-secrets, key: POSTGRES_PASSWORD } }
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec: { command: ["pg_isready", "-U", {{ .Values.postgres.user | quote }}] }
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - { name: data, mountPath: /var/lib/postgresql/data }
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- with .Values.postgres.storage.storageClass }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources: { requests: { storage: {{ .Values.postgres.storage.size }} } }
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "buktio.fullname" . }}-postgres
  labels: {{- include "buktio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "buktio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - { name: pg, port: 5432, targetPort: pg }
{{- end }}
