apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buktio.fullname" . }}-secrets
  labels: {{- include "buktio.labels" . | nindent 4 }}
type: Opaque
stringData:
  BUKTIO_MASTER_KEY: {{ required "secrets.masterKey is required" .Values.secrets.masterKey | quote }}
  GARAGE_RPC_SECRET: {{ .Values.secrets.garageRpcSecret | quote }}
  GARAGE_ADMIN_TOKEN: {{ .Values.secrets.garageAdminToken | quote }}
  GARAGE_METRICS_TOKEN: {{ .Values.secrets.garageMetricsToken | quote }}
  {{- if .Values.secrets.licenseToken }}
  BUKTIO_LICENSE_TOKEN: {{ .Values.secrets.licenseToken | quote }}
  {{- end }}
  {{- if .Values.postgres.enabled }}
  POSTGRES_PASSWORD: {{ default (randAlphaNum 24) .Values.postgres.password | quote }}
  {{- end }}
