#!/usr/bin/env bash
# Generate deploy/docker-compose/.env with random secrets. Idempotent: refuses to
# overwrite an existing .env (delete it first to regenerate).
set -euo pipefail
cd "$(dirname "$0")"

if [ -f .env ]; then
  echo ".env already exists — not overwriting. Delete it first to regenerate." >&2
  exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets" >&2
  exit 1
fi

hex32() { openssl rand -hex 32; }
hex24() { openssl rand -hex 24; }
b64_32() { openssl rand -base64 32; }

cat > .env <<EOF
# Generated by gen-env.sh — DO NOT COMMIT. Mode 600.
BUKTIO_VERSION=dev
BUKTIO_DOMAIN=localhost
BUKTIO_PUBLIC_URL=https://localhost

POSTGRES_DB=buktio
POSTGRES_USER=buktio
# hex (URL-safe) — this value is embedded in the postgres:// DATABASE_URL.
POSTGRES_PASSWORD=$(hex24)

GARAGE_RPC_SECRET=$(hex32)
GARAGE_ADMIN_TOKEN=$(b64_32)
GARAGE_METRICS_TOKEN=$(b64_32)

BUKTIO_MASTER_KEY=$(b64_32)

# Presigned URLs are signed against this host (S3 subdomain, no path rewrite).
BUKTIO_S3_PUBLIC_ENDPOINT=https://s3.localhost
# Public bucket websites: https://<bucket>.web.localhost/
BUKTIO_WEB_PUBLIC_DOMAIN=web.localhost
# Storage mode: "managed" (buktio bootstraps single-node Garage) or "external".
BUKTIO_STORAGE_MODE=managed
EOF

chmod 600 .env
echo "Wrote $(pwd)/.env (mode 600)."
